#-------------------------------------------------
#
# Project created by QtCreator 2018-02-20T21:27:10
#
#-------------------------------------------------

QT       += core gui quickwidgets charts qml network positioning location svg serialport gamepad datavisualization

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Ground_Station
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH +=   ./ ./Instruments \
                 MAVlink \
                 Eigen \


# Additional libraries:
LIBS += \
    -ldinput8 \
    -ldxguid

SOURCES += \
    Instruments/LayoutSquare.cpp \
    Instruments/qfi_ADI.cpp \
    Instruments/qfi_ALT.cpp \
    Instruments/qfi_ASI.cpp \
    Instruments/qfi_HSI.cpp \
    Instruments/qfi_NAV.cpp \
    Instruments/qfi_PFD.cpp \
    Instruments/qfi_TC.cpp \
    Instruments/qfi_VSI.cpp \
    Instruments/WidgetHSI.cpp \
    Instruments/WidgetPFD.cpp \
    Instruments/WidgetTC.cpp \
    dialog_flightcontrol.cpp \
    dialog_graphics.cpp \
    dialog_infotaxis.cpp \
    gamepad_flightcontrol.cpp \
    infotaxis.cpp \
    main.cpp \
    mainwindow.cpp \
    serialcomm.cpp \
    mavlink_interface.cpp

HEADERS += \
    Instruments/LayoutSquare.h \
    Instruments/qfi_ADI.h \
    Instruments/qfi_ALT.h \
    Instruments/qfi_ASI.h \
    Instruments/qfi_HSI.h \
    Instruments/qfi_NAV.h \
    Instruments/qfi_PFD.h \
    Instruments/qfi_TC.h \
    Instruments/qfi_VSI.h \
    Instruments/WidgetHSI.h \
    Instruments/WidgetPFD.h \
    Instruments/WidgetTC.h \
    MAVlink/ardupilotmega/ardupilotmega.h \
    MAVlink/ardupilotmega/mavlink.h \
    MAVlink/ardupilotmega/mavlink_msg_adap_tuning.h \
    MAVlink/ardupilotmega/mavlink_msg_ahrs.h \
    MAVlink/ardupilotmega/mavlink_msg_ahrs2.h \
    MAVlink/ardupilotmega/mavlink_msg_ahrs3.h \
    MAVlink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    MAVlink/ardupilotmega/mavlink_msg_aoa_ssa.h \
    MAVlink/ardupilotmega/mavlink_msg_ap_adc.h \
    MAVlink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    MAVlink/ardupilotmega/mavlink_msg_battery2.h \
    MAVlink/ardupilotmega/mavlink_msg_camera_feedback.h \
    MAVlink/ardupilotmega/mavlink_msg_camera_status.h \
    MAVlink/ardupilotmega/mavlink_msg_compassmot_status.h \
    MAVlink/ardupilotmega/mavlink_msg_data16.h \
    MAVlink/ardupilotmega/mavlink_msg_data32.h \
    MAVlink/ardupilotmega/mavlink_msg_data64.h \
    MAVlink/ardupilotmega/mavlink_msg_data96.h \
    MAVlink/ardupilotmega/mavlink_msg_deepstall.h \
    MAVlink/ardupilotmega/mavlink_msg_device_op_read.h \
    MAVlink/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    MAVlink/ardupilotmega/mavlink_msg_device_op_write.h \
    MAVlink/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    MAVlink/ardupilotmega/mavlink_msg_digicam_configure.h \
    MAVlink/ardupilotmega/mavlink_msg_digicam_control.h \
    MAVlink/ardupilotmega/mavlink_msg_ekf_status_report.h \
    MAVlink/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.h \
    MAVlink/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.h \
    MAVlink/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.h \
    MAVlink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    MAVlink/ardupilotmega/mavlink_msg_fence_point.h \
    MAVlink/ardupilotmega/mavlink_msg_fence_status.h \
    MAVlink/ardupilotmega/mavlink_msg_gimbal_control.h \
    MAVlink/ardupilotmega/mavlink_msg_gimbal_report.h \
    MAVlink/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    MAVlink/ardupilotmega/mavlink_msg_gopro_get_request.h \
    MAVlink/ardupilotmega/mavlink_msg_gopro_get_response.h \
    MAVlink/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    MAVlink/ardupilotmega/mavlink_msg_gopro_set_request.h \
    MAVlink/ardupilotmega/mavlink_msg_gopro_set_response.h \
    MAVlink/ardupilotmega/mavlink_msg_hwstatus.h \
    MAVlink/ardupilotmega/mavlink_msg_led_control.h \
    MAVlink/ardupilotmega/mavlink_msg_limits_status.h \
    MAVlink/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    MAVlink/ardupilotmega/mavlink_msg_mag_cal_report.h \
    MAVlink/ardupilotmega/mavlink_msg_meminfo.h \
    MAVlink/ardupilotmega/mavlink_msg_mount_configure.h \
    MAVlink/ardupilotmega/mavlink_msg_mount_control.h \
    MAVlink/ardupilotmega/mavlink_msg_mount_status.h \
    MAVlink/ardupilotmega/mavlink_msg_pid_tuning.h \
    MAVlink/ardupilotmega/mavlink_msg_radio.h \
    MAVlink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    MAVlink/ardupilotmega/mavlink_msg_rally_point.h \
    MAVlink/ardupilotmega/mavlink_msg_rangefinder.h \
    MAVlink/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    MAVlink/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    MAVlink/ardupilotmega/mavlink_msg_rpm.h \
    MAVlink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    MAVlink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    MAVlink/ardupilotmega/mavlink_msg_simstate.h \
    MAVlink/ardupilotmega/mavlink_msg_vision_position_delta.h \
    MAVlink/ardupilotmega/mavlink_msg_wind.h \
    MAVlink/ardupilotmega/testsuite.h \
    MAVlink/ardupilotmega/version.h \
    MAVlink/ASLUAV/ASLUAV.h \
    MAVlink/ASLUAV/mavlink.h \
    MAVlink/ASLUAV/mavlink_msg_asl_obctrl.h \
    MAVlink/ASLUAV/mavlink_msg_aslctrl_data.h \
    MAVlink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    MAVlink/ASLUAV/mavlink_msg_asluav_status.h \
    MAVlink/ASLUAV/mavlink_msg_command_int_stamped.h \
    MAVlink/ASLUAV/mavlink_msg_command_long_stamped.h \
    MAVlink/ASLUAV/mavlink_msg_ekf_ext.h \
    MAVlink/ASLUAV/mavlink_msg_fw_soaring_data.h \
    MAVlink/ASLUAV/mavlink_msg_gsm_link_status.h \
    MAVlink/ASLUAV/mavlink_msg_sens_atmos.h \
    MAVlink/ASLUAV/mavlink_msg_sens_batmon.h \
    MAVlink/ASLUAV/mavlink_msg_sens_mppt.h \
    MAVlink/ASLUAV/mavlink_msg_sens_power.h \
    MAVlink/ASLUAV/mavlink_msg_sens_power_board.h \
    MAVlink/ASLUAV/mavlink_msg_sensorpod_status.h \
    MAVlink/ASLUAV/testsuite.h \
    MAVlink/ASLUAV/version.h \
    MAVlink/autoquad/autoquad.h \
    MAVlink/autoquad/mavlink.h \
    MAVlink/autoquad/mavlink_msg_aq_esc_telemetry.h \
    MAVlink/autoquad/mavlink_msg_aq_telemetry_f.h \
    MAVlink/autoquad/testsuite.h \
    MAVlink/autoquad/version.h \
    MAVlink/common/common.h \
    MAVlink/common/mavlink.h \
    MAVlink/common/mavlink_msg_actuator_control_target.h \
    MAVlink/common/mavlink_msg_adsb_vehicle.h \
    MAVlink/common/mavlink_msg_altitude.h \
    MAVlink/common/mavlink_msg_att_pos_mocap.h \
    MAVlink/common/mavlink_msg_attitude.h \
    MAVlink/common/mavlink_msg_attitude_quaternion.h \
    MAVlink/common/mavlink_msg_attitude_quaternion_cov.h \
    MAVlink/common/mavlink_msg_attitude_target.h \
    MAVlink/common/mavlink_msg_auth_key.h \
    MAVlink/common/mavlink_msg_autopilot_version.h \
    MAVlink/common/mavlink_msg_battery_status.h \
    MAVlink/common/mavlink_msg_button_change.h \
    MAVlink/common/mavlink_msg_camera_capture_status.h \
    MAVlink/common/mavlink_msg_camera_image_captured.h \
    MAVlink/common/mavlink_msg_camera_information.h \
    MAVlink/common/mavlink_msg_camera_settings.h \
    MAVlink/common/mavlink_msg_camera_trigger.h \
    MAVlink/common/mavlink_msg_cellular_status.h \
    MAVlink/common/mavlink_msg_change_operator_control.h \
    MAVlink/common/mavlink_msg_change_operator_control_ack.h \
    MAVlink/common/mavlink_msg_collision.h \
    MAVlink/common/mavlink_msg_command_ack.h \
    MAVlink/common/mavlink_msg_command_int.h \
    MAVlink/common/mavlink_msg_command_long.h \
    MAVlink/common/mavlink_msg_control_system_state.h \
    MAVlink/common/mavlink_msg_data_stream.h \
    MAVlink/common/mavlink_msg_data_transmission_handshake.h \
    MAVlink/common/mavlink_msg_debug.h \
    MAVlink/common/mavlink_msg_debug_float_array.h \
    MAVlink/common/mavlink_msg_debug_vect.h \
    MAVlink/common/mavlink_msg_distance_sensor.h \
    MAVlink/common/mavlink_msg_encapsulated_data.h \
    MAVlink/common/mavlink_msg_estimator_status.h \
    MAVlink/common/mavlink_msg_extended_sys_state.h \
    MAVlink/common/mavlink_msg_file_transfer_protocol.h \
    MAVlink/common/mavlink_msg_flight_information.h \
    MAVlink/common/mavlink_msg_follow_target.h \
    MAVlink/common/mavlink_msg_global_position_int.h \
    MAVlink/common/mavlink_msg_global_position_int_cov.h \
    MAVlink/common/mavlink_msg_global_vision_position_estimate.h \
    MAVlink/common/mavlink_msg_gps2_raw.h \
    MAVlink/common/mavlink_msg_gps2_rtk.h \
    MAVlink/common/mavlink_msg_gps_global_origin.h \
    MAVlink/common/mavlink_msg_gps_inject_data.h \
    MAVlink/common/mavlink_msg_gps_input.h \
    MAVlink/common/mavlink_msg_gps_raw_int.h \
    MAVlink/common/mavlink_msg_gps_rtcm_data.h \
    MAVlink/common/mavlink_msg_gps_rtk.h \
    MAVlink/common/mavlink_msg_gps_status.h \
    MAVlink/common/mavlink_msg_heartbeat.h \
    MAVlink/common/mavlink_msg_high_latency.h \
    MAVlink/common/mavlink_msg_high_latency2.h \
    MAVlink/common/mavlink_msg_highres_imu.h \
    MAVlink/common/mavlink_msg_hil_actuator_controls.h \
    MAVlink/common/mavlink_msg_hil_controls.h \
    MAVlink/common/mavlink_msg_hil_gps.h \
    MAVlink/common/mavlink_msg_hil_optical_flow.h \
    MAVlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    MAVlink/common/mavlink_msg_hil_sensor.h \
    MAVlink/common/mavlink_msg_hil_state.h \
    MAVlink/common/mavlink_msg_hil_state_quaternion.h \
    MAVlink/common/mavlink_msg_home_position.h \
    MAVlink/common/mavlink_msg_landing_target.h \
    MAVlink/common/mavlink_msg_local_position_ned.h \
    MAVlink/common/mavlink_msg_local_position_ned_cov.h \
    MAVlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    MAVlink/common/mavlink_msg_log_data.h \
    MAVlink/common/mavlink_msg_log_entry.h \
    MAVlink/common/mavlink_msg_log_erase.h \
    MAVlink/common/mavlink_msg_log_request_data.h \
    MAVlink/common/mavlink_msg_log_request_end.h \
    MAVlink/common/mavlink_msg_log_request_list.h \
    MAVlink/common/mavlink_msg_logging_ack.h \
    MAVlink/common/mavlink_msg_logging_data.h \
    MAVlink/common/mavlink_msg_logging_data_acked.h \
    MAVlink/common/mavlink_msg_manual_control.h \
    MAVlink/common/mavlink_msg_manual_setpoint.h \
    MAVlink/common/mavlink_msg_memory_vect.h \
    MAVlink/common/mavlink_msg_message_interval.h \
    MAVlink/common/mavlink_msg_mission_ack.h \
    MAVlink/common/mavlink_msg_mission_clear_all.h \
    MAVlink/common/mavlink_msg_mission_count.h \
    MAVlink/common/mavlink_msg_mission_current.h \
    MAVlink/common/mavlink_msg_mission_item.h \
    MAVlink/common/mavlink_msg_mission_item_int.h \
    MAVlink/common/mavlink_msg_mission_item_reached.h \
    MAVlink/common/mavlink_msg_mission_request.h \
    MAVlink/common/mavlink_msg_mission_request_int.h \
    MAVlink/common/mavlink_msg_mission_request_list.h \
    MAVlink/common/mavlink_msg_mission_request_partial_list.h \
    MAVlink/common/mavlink_msg_mission_set_current.h \
    MAVlink/common/mavlink_msg_mission_write_partial_list.h \
    MAVlink/common/mavlink_msg_mount_orientation.h \
    MAVlink/common/mavlink_msg_named_value_float.h \
    MAVlink/common/mavlink_msg_named_value_int.h \
    MAVlink/common/mavlink_msg_nav_controller_output.h \
    MAVlink/common/mavlink_msg_obstacle_distance.h \
    MAVlink/common/mavlink_msg_odometry.h \
    MAVlink/common/mavlink_msg_optical_flow.h \
    MAVlink/common/mavlink_msg_optical_flow_rad.h \
    MAVlink/common/mavlink_msg_orbit_execution_status.h \
    MAVlink/common/mavlink_msg_param_ext_ack.h \
    MAVlink/common/mavlink_msg_param_ext_request_list.h \
    MAVlink/common/mavlink_msg_param_ext_request_read.h \
    MAVlink/common/mavlink_msg_param_ext_set.h \
    MAVlink/common/mavlink_msg_param_ext_value.h \
    MAVlink/common/mavlink_msg_param_map_rc.h \
    MAVlink/common/mavlink_msg_param_request_list.h \
    MAVlink/common/mavlink_msg_param_request_read.h \
    MAVlink/common/mavlink_msg_param_set.h \
    MAVlink/common/mavlink_msg_param_value.h \
    MAVlink/common/mavlink_msg_ping.h \
    MAVlink/common/mavlink_msg_play_tune.h \
    MAVlink/common/mavlink_msg_position_target_global_int.h \
    MAVlink/common/mavlink_msg_position_target_local_ned.h \
    MAVlink/common/mavlink_msg_power_status.h \
    MAVlink/common/mavlink_msg_protocol_version.h \
    MAVlink/common/mavlink_msg_radio_status.h \
    MAVlink/common/mavlink_msg_raw_imu.h \
    MAVlink/common/mavlink_msg_raw_pressure.h \
    MAVlink/common/mavlink_msg_rc_channels.h \
    MAVlink/common/mavlink_msg_rc_channels_override.h \
    MAVlink/common/mavlink_msg_rc_channels_raw.h \
    MAVlink/common/mavlink_msg_rc_channels_scaled.h \
    MAVlink/common/mavlink_msg_request_data_stream.h \
    MAVlink/common/mavlink_msg_resource_request.h \
    MAVlink/common/mavlink_msg_safety_allowed_area.h \
    MAVlink/common/mavlink_msg_safety_set_allowed_area.h \
    MAVlink/common/mavlink_msg_scaled_imu.h \
    MAVlink/common/mavlink_msg_scaled_imu2.h \
    MAVlink/common/mavlink_msg_scaled_imu3.h \
    MAVlink/common/mavlink_msg_scaled_pressure.h \
    MAVlink/common/mavlink_msg_scaled_pressure2.h \
    MAVlink/common/mavlink_msg_scaled_pressure3.h \
    MAVlink/common/mavlink_msg_serial_control.h \
    MAVlink/common/mavlink_msg_servo_output_raw.h \
    MAVlink/common/mavlink_msg_set_actuator_control_target.h \
    MAVlink/common/mavlink_msg_set_attitude_target.h \
    MAVlink/common/mavlink_msg_set_gps_global_origin.h \
    MAVlink/common/mavlink_msg_set_home_position.h \
    MAVlink/common/mavlink_msg_set_mode.h \
    MAVlink/common/mavlink_msg_set_position_target_global_int.h \
    MAVlink/common/mavlink_msg_set_position_target_local_ned.h \
    MAVlink/common/mavlink_msg_setup_signing.h \
    MAVlink/common/mavlink_msg_sim_state.h \
    MAVlink/common/mavlink_msg_smart_battery_info.h \
    MAVlink/common/mavlink_msg_smart_battery_status.h \
    MAVlink/common/mavlink_msg_statustext.h \
    MAVlink/common/mavlink_msg_statustext_long.h \
    MAVlink/common/mavlink_msg_storage_information.h \
    MAVlink/common/mavlink_msg_sys_status.h \
    MAVlink/common/mavlink_msg_system_time.h \
    MAVlink/common/mavlink_msg_terrain_check.h \
    MAVlink/common/mavlink_msg_terrain_data.h \
    MAVlink/common/mavlink_msg_terrain_report.h \
    MAVlink/common/mavlink_msg_terrain_request.h \
    MAVlink/common/mavlink_msg_timesync.h \
    MAVlink/common/mavlink_msg_trajectory_representation_bezier.h \
    MAVlink/common/mavlink_msg_trajectory_representation_waypoints.h \
    MAVlink/common/mavlink_msg_uavcan_node_info.h \
    MAVlink/common/mavlink_msg_uavcan_node_status.h \
    MAVlink/common/mavlink_msg_utm_global_position.h \
    MAVlink/common/mavlink_msg_v2_extension.h \
    MAVlink/common/mavlink_msg_vfr_hud.h \
    MAVlink/common/mavlink_msg_vibration.h \
    MAVlink/common/mavlink_msg_vicon_position_estimate.h \
    MAVlink/common/mavlink_msg_video_stream_information.h \
    MAVlink/common/mavlink_msg_video_stream_status.h \
    MAVlink/common/mavlink_msg_vision_position_estimate.h \
    MAVlink/common/mavlink_msg_vision_speed_estimate.h \
    MAVlink/common/mavlink_msg_wheel_distance.h \
    MAVlink/common/mavlink_msg_wifi_config_ap.h \
    MAVlink/common/mavlink_msg_wind_cov.h \
    MAVlink/common/testsuite.h \
    MAVlink/common/version.h \
    MAVlink/icarous/icarous.h \
    MAVlink/icarous/mavlink.h \
    MAVlink/icarous/mavlink_msg_icarous_heartbeat.h \
    MAVlink/icarous/mavlink_msg_icarous_kinematic_bands.h \
    MAVlink/icarous/testsuite.h \
    MAVlink/icarous/version.h \
    MAVlink/matrixpilot/matrixpilot.h \
    MAVlink/matrixpilot/mavlink.h \
    MAVlink/matrixpilot/mavlink_msg_airspeeds.h \
    MAVlink/matrixpilot/mavlink_msg_altitudes.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_command.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    MAVlink/matrixpilot/mavlink_msg_flexifunction_set.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    MAVlink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    MAVlink/matrixpilot/testsuite.h \
    MAVlink/matrixpilot/version.h \
    MAVlink/minimal/mavlink.h \
    MAVlink/minimal/mavlink_msg_heartbeat.h \
    MAVlink/minimal/minimal.h \
    MAVlink/minimal/testsuite.h \
    MAVlink/minimal/version.h \
    MAVlink/slugs/mavlink.h \
    MAVlink/slugs/mavlink_msg_boot.h \
    MAVlink/slugs/mavlink_msg_control_surface.h \
    MAVlink/slugs/mavlink_msg_cpu_load.h \
    MAVlink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    MAVlink/slugs/mavlink_msg_data_log.h \
    MAVlink/slugs/mavlink_msg_diagnostic.h \
    MAVlink/slugs/mavlink_msg_gps_date_time.h \
    MAVlink/slugs/mavlink_msg_isr_location.h \
    MAVlink/slugs/mavlink_msg_mid_lvl_cmds.h \
    MAVlink/slugs/mavlink_msg_novatel_diag.h \
    MAVlink/slugs/mavlink_msg_ptz_status.h \
    MAVlink/slugs/mavlink_msg_sensor_bias.h \
    MAVlink/slugs/mavlink_msg_sensor_diag.h \
    MAVlink/slugs/mavlink_msg_slugs_camera_order.h \
    MAVlink/slugs/mavlink_msg_slugs_configuration_camera.h \
    MAVlink/slugs/mavlink_msg_slugs_mobile_location.h \
    MAVlink/slugs/mavlink_msg_slugs_navigation.h \
    MAVlink/slugs/mavlink_msg_status_gps.h \
    MAVlink/slugs/mavlink_msg_uav_status.h \
    MAVlink/slugs/mavlink_msg_volt_sensor.h \
    MAVlink/slugs/slugs.h \
    MAVlink/slugs/testsuite.h \
    MAVlink/slugs/version.h \
    MAVlink/standard/mavlink.h \
    MAVlink/standard/standard.h \
    MAVlink/standard/testsuite.h \
    MAVlink/standard/version.h \
    MAVlink/test/mavlink.h \
    MAVlink/test/mavlink_msg_test_types.h \
    MAVlink/test/test.h \
    MAVlink/test/testsuite.h \
    MAVlink/test/version.h \
    MAVlink/uAvionix/mavlink.h \
    MAVlink/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    MAVlink/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    MAVlink/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    MAVlink/uAvionix/testsuite.h \
    MAVlink/uAvionix/uAvionix.h \
    MAVlink/uAvionix/version.h \
    MAVlink/checksum.h \
    MAVlink/mavlink_conversions.h \
    MAVlink/mavlink_get_info.h \
    MAVlink/mavlink_helpers.h \
    MAVlink/mavlink_sha256.h \
    MAVlink/mavlink_types.h \
    MAVlink/protocol.h \
    dialog_flightcontrol.h \
    dialog_graphics.h \
    dialog_infotaxis.h \
    gamepad_flightcontrol.h \
    infotaxis.h \
    mainwindow.h \
    serialcomm.h \
    mavlink_interface.h

FORMS += \
    dialog_graphics.ui \
    dialog_infotaxis.ui \
        mainwindow.ui \
    Instruments/WidgetHSI.ui \
    Instruments/WidgetPFD.ui \
    Instruments/WidgetTC.ui \
    dialog_flightcontrol.ui

RESOURCES += \
    qfi.qrc \
    mapbox.qrc

DISTFILES +=
